
[cursor.style]
blinking = "On"
shape = "Underline"

[font]
size = 9

[font.bold]
family = "RobotoMono Nerd Font"
style = "Bold"

[font.bold_italic]
family = "RobotoMono Nerd Font"
style = "Bold Italic"

[font.italic]
family = "RobotoMono Nerd Font"
style = "Italic"

[font.normal]
family = "RobotoMono Nerd Font"
style = "Regular"

[window]
dynamic_padding = true
opacity = 0.975

[window.padding]
x = 5
y = 5

[general]
import = ["/home/xelser/.config/alacritty/gruvbox-material.toml"]
