
[cursor.style]
blinking = "On"
shape = "Underline"

[font]
size = 9

[font.bold]
family = "RobotoMono Nerd Font"
style = "Bold"

[font.bold_italic]
family = "RobotoMono Nerd Font"
style = "Bold Italic"

[font.italic]
family = "RobotoMono Nerd Font"
style = "Medium Italic"

[font.normal]
family = "RobotoMono Nerd Font"
style = "Medium"

[window]
dynamic_padding = true
opacity = 0.6

[window.padding]
x = 5
y = 5

[general]
ipc_socket = true
import = ["~/.config/alacritty/themes/themes/gruvbox_material_hard_dark.toml"]
