import = ["/home/xelser/.config/alacritty/catppuccin/catppuccin-mocha.toml"]

[env]
TERM = "xterm-256color"

[cursor.style]
blinking = "On"
shape = "Underline"

[font]
size = 9

[font.bold]
family = "FiraCode Nerd Font"
style = "Bold"

[font.bold_italic]
family = "FiraCode Nerd Font"
style = "Bold Italic"

[font.italic]
family = "FiraCode Nerd Font"
style = "Italic"

[font.normal]
family = "FiraCode Nerd Font"
style = "Medium"

[window]
dynamic_padding = true
opacity = 0.95

[window.padding]
x = 5
y = 5
