[general]
ipc_socket = true
live_config_reload = true
import = ["~/.config/alacritty/gruvbox-material-hard-dark.toml"]

[cursor]
style = { shape = "Underline", blinking = "On" }

[font]
size = 10

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Medium"

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Italic"

[font.bold_italic]
family = "JetBrainsMono Nerd Font"
style = "Bold Italic"

[window]
padding = { x = 5, y = 5 }
dynamic_padding = true
opacity = 0.9
