[cursor.style]
blinking = "On"
shape = "Underline"

[font]
size = 9

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.bold_italic]
family = "JetBrainsMono Nerd Font"
style = "Bold Italic"

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Italic"

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Medium"

[window]
dynamic_padding = true
opacity = 0.4

[window.padding]
x = 5
y = 5

[general]
ipc_socket = true
import = ["/usr/share/alacritty/themes/gruvbox_material_hard_dark.toml"]
