[Base]
CopyFilenameToClipboard=0
autoSave=false
autoSaveFirst=false
defDir=/home/xelser/Pictures/Screenshots/
defFilename=screen
defImgFormat=png
defScreenshotType=FullScreen
delay=0
imageQuality=80
includeCursor=true
insDateTimeInFilename=true
noDecorations=false
templateDateTime=yyyy-MM-dd-hh-mm-ss

[Display]
lastSelection=@Rect(449 217 712 429)
showTrayIcon=false
timeTrayMessages=5
trayMessages=1
windowHeight=534
windowWidth=618
zoomAroundMouse=false

[GlobalShortcuts]
ActiveWindow=
AreaSelection=
FullScreen=

[LocalShortcuts]
Close=Esc
CopyScreen=Ctrl+C
Help=F1
NewScreen=Ctrl+N
Options=Ctrl+P
SaveScreen=Ctrl+S

[System]
AllowCopies=true
closeInTray=false
enbaleExternalView=true
fitInside=true
