system:
  game_path: /run/media/xelser/Shared/Games
  locale: ''
  mangohud: true
  vk_icd: /usr/lib/x86_64-linux-gnu/GL/vulkan/icd.d/nvidia_icd.json:/usr/lib/i386-linux-gnu/GL/vulkan/icd.d/nvidia_icd.json
