
# package managers
if [ -f /usr/bin/apt ]; then
	alias update="sudo apt update && sudo apt upgrade --yes"
	alias install="sudo apt install $1"
	alias uninstall="sudo apt autoremove --purge $1"
	alias clean="sudo apt autoremove --purge --yes && sudo apt autoclean"
	alias search="sudo apt search $1"
	alias list="sudo apt list --installed | cut -d '/' -f1 | grep $1"
elif [ -f /usr/bin/pacman ]; then
	alias update="sudo pacman -Syyu --noconfirm"
	alias install="sudo pacman -S $1 --needed"
	alias uninstall="sudo pacman -Rnsu $1"
	alias clean="sudo pacman -Qtdq | sudo pacman -Rnsu - --noconfirm 1> /dev/null; sudo pacman -Sc --noconfirm"
	alias search="sudo pacman -Ss $1"
	alias list="sudo pacman -Qq $1"
elif [ -f /usr/bin/dnf ]; then
	alias update="sudo dnf upgrade --assumeyes --allowerasing"
	alias install="sudo dnf install $1"
	alias uninstall="sudo dnf remove $1"
	alias clean="sudo dnf autoremove --assumeyes && sudo dnf clean all"
	alias search="sudo dnf search $1"
	alias list="sudo dnf list --installed $1"
fi

if [ -f /usr/bin/yay ]; then
	alias updateaur="yay -Syyu --noconfirm"
	alias installaur="yay -S $1 --needed"
	alias uninstallaur="yay -Rnsu $1"
	alias cleanaur="yay -Qtdq | yay -Rnsu - --noconfirm 1> /dev/null; sudo pacman -Sc --noconfirm"
	alias searchaur="yay -Ss $1"
	alias listaur="yay -Qq $1"
fi

if [ -f /usr/bin/flatpak ]; then
	alias updateflat="flatpak update --assumeyes"
	alias installflat="flatpak install flathub $1"
	alias uninstallflat="flatpak uninstall $1"
	alias cleanflat="flatpak uninstall --unused --delete-data --assumeyes"
	alias searchflat="flatpak search --columns=name,application,version,branch $1"
fi

# GNOME Shell Extensions
[ -f $HOME/.local/bin/gext ] && alias gextup="gext update --user --install"

# editors
alias edit="nvim"

# dotfiles
if [ -d $HOME/Documents/distro-scripts/ ] ; then
	alias bashaliasesup="cat $HOME/Documents/distro-scripts/common/bash_aliases > $HOME/.bash_aliases && source $HOME/.bash_aliases"
	alias bashprofileup="cat $HOME/Documents/distro-scripts/common/bash_profile > $HOME/.bash_profile && source $HOME/.bash_profile"
	alias bashup="bashaliasesup && bashprofileup"
	alias dotup="bash $HOME/Documents/distro-scripts/common/update-dotfiles.sh"
	alias gitpull="git fetch && git pull"
	alias gitcommit="git add . && git commit -m 'auto-update @ $(hostname)' && git push"
	alias gitupdate="cd $HOME/Documents/distro-scripts && gitpull ; bashup ; dotup ; gitcommit ; cd $HOME"
fi

# others
alias updateall="update ; updateflat ; [ -d $HOME/Documents/distro-scripts/ ] && gitupdate"
alias fetch="[ -f /bin/fastfetch ] && fastfetch || neofetch"
alias lock="[ -f /usr/bin/betterlockscreen ] && betterlockscreen -l dimblur >1 /dev/null"
alias post="bash $HOME/.config/post.sh"
alias refresh="source $HOME/.bashrc"
alias clear="clear && history -c"


