[Application]
FileLogger\Age=1
FileLogger\AgeType=1
FileLogger\Backup=true
FileLogger\DeleteOld=true
FileLogger\Enabled=true
FileLogger\MaxSizeBytes=66560
FileLogger\Path=/home/xelser/.local/share/qBittorrent/logs

[BitTorrent]
Session\DefaultSavePath=/mnt/Orico/Downloads
Session\ExcludedFileNames=
Session\MaxConnections=50
Session\MaxConnectionsPerTorrent=15
Session\MaxUploads=5
Session\MaxUploadsPerTorrent=2
Session\Port=48068
Session\QueueingSystemEnabled=false
Session\SSL\Port=5200

[Core]
AutoDeleteAddedTorrentFile=Never

[LegalNotice]
Accepted=true

[Meta]
MigrationVersion=8

[Preferences]
General\Locale=en
MailNotification\req_auth=true
WebUI\AuthSubnetWhitelist=@Invalid()
WebUI\Password_PBKDF2="@ByteArray(azAjgQW1JNyM8lILqdCJYw==:g7N7NMNVnidJW1zXKJNGCTLQ4ImptTeQ7gufHInuV2VQpxXyooiiAYWiDlmQBXA4BpRWoyHAiQyGswxc2K9epA==)"
WebUI\Username=xelser

[RSS]
AutoDownloader\DownloadRepacks=true
AutoDownloader\SmartEpisodeFilter=s(\\d+)e(\\d+), (\\d+)x(\\d+), "(\\d{4}[.\\-]\\d{1,2}[.\\-]\\d{1,2})", "(\\d{1,2}[.\\-]\\d{1,2}[.\\-]\\d{4})"
