[mainwindow]
geometry=@ByteArray(\x1\xd9\xd0\xcb\0\x3\0\0\0\0\0\0\0\0\0\0\0\0\x5U\0\0\x2\xd7\0\0\x1\x81\0\0\0\xc5\0\0\x3\xd8\0\0\x2|\0\0\0\0\x2\0\0\0\x5V\0\0\0\0\0\0\0!\0\0\x5U\0\0\x2\xd7)
maximized=true
pos=@Point(381 131)
savestate=@ByteArray(\0\0\0\xff\0\0\0\0\xfd\0\0\0\0\0\0\x5V\0\0\x2\xb7\0\0\0\x4\0\0\0\x4\0\0\0\b\0\0\0\b\xfc\0\0\0\0)
size=@Size(600 440)

[notifications]
checkLanguagePackages=false
checkNewKernel=false
checkNewKernelLts=false
checkNewKernelRecommended=false
checkUnsupportedKernel=false
checkUnsupportedKernelRunning=false
